spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${ONMOM_DATASOURCE_URL:${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/onmom-local}}
spring.datasource.username=${ONMOM_DATASOURCE_USERNAME:${SPRING_DATASOURCE_USERNAME:onmom_user}}
spring.datasource.password=${ONMOM_DATASOURCE_PASSWORD:${SPRING_DATASOURCE_PASSWORD:onmom_password}}
